In [1]:
import numpy as np
import pandas as pd

In [17]:
input = np.random.random((3,10))
print(f"shape of input : {input.shape}")
[ row , column] = input.shape
# row
# column

shape of input : (3, 10)


In [18]:
input

array([[0.2909535 , 0.39661276, 0.71951256, 0.45063354, 0.49487895,
        0.052418  , 0.93794137, 0.20098265, 0.75871109, 0.49653295],
       [0.39011825, 0.59080985, 0.83940213, 0.14539357, 0.91161089,
        0.35717575, 0.23024512, 0.62672858, 0.63431337, 0.67463805],
       [0.46813799, 0.92488638, 0.96018808, 0.04936579, 0.02550428,
        0.52411226, 0.08862384, 0.56353344, 0.39934746, 0.09000198]])

In [21]:
oneD = np.ones((1,10), dtype='int')
oneD

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [28]:
A = np.random.random((10,3)) # A -> (10x3)
B = np.random.random((3,10)) # B -> (3x10)

np.dot(A,B) == A @ B
# In context of matrices both achieves rhe same results 

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [52]:
# Input vector looks lik 3*1 [Input : I]
inputVector = np.random.random((3,1)) 
inputVector.shape
print(f"inputVector : {inputVector}")

# First Layer will have 4 nodes
FirstLayerWights = np.ones((4,3))
print(f"FirstLayerWights : {FirstLayerWights}")

# y = W @ I
FirstLayerSimple = FirstLayerWights @ inputVector 
print(f"FirstLayerSimple : {FirstLayerSimple}")


def sigmoid(x):
    """_summary_
    It calculates the sigmoid of anything
    """
    return 1 / ( 1 + np.exp(-x))


FirstLayerAfterActivation = sigmoid(FirstLayerSimple)
print(f"FirstLayerAfterActivation : {FirstLayerAfterActivation}")


expectedOutput = np.random.random((4,1))
print(f"expectedOutput : {expectedOutput}")


# Error Calculation  E = (Ypred -Yactual)^2 / N
diff =  FirstLayerAfterActivation - expectedOutput
Error = diff.T @ diff  
print(f"Error : {Error}")

# Gradient Descent 
grad =  ( FirstLayerAfterActivation - expectedOutput ) @ inputVector.T
print(f"grad :  {grad}")


# Back-propagation
LearningRateAlpha = 0.0001

# Weights update First Layer will be updated
FirstLayerWightsUpdated = FirstLayerWights - LearningRateAlpha * grad
print(f"FirstLayerWightsUpdated : {FirstLayerWightsUpdated}")



inputVector : [[0.92628275]
 [0.59172401]
 [0.09569885]]
FirstLayerWights : [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
FirstLayerSimple : [[1.61370561]
 [1.61370561]
 [1.61370561]
 [1.61370561]]
FirstLayerAfterActivation : [[0.83392523]
 [0.83392523]
 [0.83392523]
 [0.83392523]]
expectedOutput : [[0.22666437]
 [0.70136489]
 [0.44579536]
 [0.82130741]]
Error : [[0.53714198]]
grad :  [[0.56249525 0.35933083 0.05811416]
 [0.12278835 0.07843913 0.01268587]
 [0.359518   0.22966576 0.03714358]
 [0.01168766 0.00746626 0.00120751]]
FirstLayerWightsUpdated : [[0.99994375 0.99996407 0.99999419]
 [0.99998772 0.99999216 0.99999873]
 [0.99996405 0.99997703 0.99999629]
 [0.99999883 0.99999925 0.99999988]]
